bower.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/1)
=> Update Bower configuration

bower.json, test/chart-empty-test.html, test/chart-multiple-test.html, test/chart-with-data-test.html, test/index.html, test/multiple-series-test.html, test/pie-config-test.html, v-chart-series.html, v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/4)
=> Add tests and fix execution in other browsers (CHARTS-121)

v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/5)
=> Fix default property value declaration (CHARTS-121)

.gitignore, config/default.json, config/local.json.example, gulpfile.js, tasks/demo.js, tasks/zip.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/9)
=> Add build targets for demo, include full demo folder in zip (CHARTS-165)

bower.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/12)
=> Update Polymer and PolymerElements versions to 1.0.0

demo/demo-column-drilldown.html, demo/demo-picker.html, demo/demo-treemap-coloraxis.html, test/index.html, test/series-point-elements-data.html, v-chart.html, v-series.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/13)
=> Add support for object lists in series data (CHARTS-162)

test/index.html, test/series-point-elements-date-data.html, v-chart.html, v-series.html
Inner text of date element should be a valid date using ISO8601 date format
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/14)
=> Support date element to set x value in point (CHARTS-163)

demo/column_and_bar/bar-with-negative-stack.html, demo/column_and_bar/basic-bar.html, demo/column_and_bar/basic-column.html, demo/column_and_bar/column-with-multi-level-drilldown.html, demo/column_and_bar/column-with-native-drilldown.html, demo/column_and_bar/column-with-negative-values.html, demo/column_and_bar/column-with-rotated-labels.html, demo/column_and_bar/dual-axes-line-and-column.html, demo/column_and_bar/stacked-and-grouped-column.html, demo/column_and_bar/stacked-bar.html, demo/column_and_bar/stacked-column.html, demo/column_and_bar/stacked-percentage-column.html, demo/demo-picker.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/15)
=> Implement Column and Bar demos (CHARTS-171)

demo/demo-picker.html, demo/other/treemap-with-color-axis.html, demo/pie/donut.html, demo/pie/pie-with-credits.html, demo/pie/pie-with-gradient-fill.html, demo/pie/pie-with-legend.html, demo/pie/pie-with-start-and-end-angle.html, demo/pie/pie.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/16)
=> Implement Pie demos (CHARTS-172)

demo/area/area-spline.html, demo/area/area-with-missing-points.html, demo/area/area-with-negative-values.html, demo/area/basic-area.html, demo/area/inverted-axes.html, demo/area/percentage-area.html, demo/area/stacked-area.html, demo/demo-picker.html, v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/17)
=> Implement Area Demos (CHARTS-173)

demo/line_and_scatter/spline-with-symbols.html, test/index.html, test/series-multiple-data-elements.html, v-series.html
Also fix test failure in safari due to absence of string startsWith
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/23)
=> Enable multiple adding multiple Data elements to a v-series (CHARTS-181)

configuration-reader.html, wct.conf.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/26)
=> Run verification build for Github pull requests (CHARTS-170)

demo/line_and_scatter/basic-line-with-callouts.html, demo/line_and_scatter/spline-with-symbols.html, demo/other/clock.html, demo/pie/pie-with-gradient-fill.html, test/series-markers.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/27)
=> Converted json configuration into xml CHARTS-195

demo/binding/rest-multiple-series-data.html, demo/binding/wc-data-example.html, demo/dynamic/master-detail-chart.html, demo/prettify-element.html, demo/sourcing-component.html, v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/31)
=> Remove reflow workaround and fix affected demos (CHARTS-209)

demo/demo-picker.html, demo/sourcing-component.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/33)
=> Fix demo source selection and color (CHARTS-216)

test/chart-load-event-test.html, test/index.html, v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/34)
=> As a developer, I want to get an event when the chart has been loaded (CHARTS-208)

test/binding-test.html, test/chart-reload-test.html, test/index.html, v-chart.html, v-series.html, wct.conf.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/37)
=> Add v-chart reloadConfiguration method (CHARTS-211)

bower.json, tasks/zip.js, v-chart.html
Also fixes fonts for staged demo
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/38)
=> As a developer, I want Vaadin Charts to depend on a specific Highcharts version (CHARTS-205)

wct.conf.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/42)
=> Add Edge to test browser config (CHARTS-229)

bower.json, v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/41)
=> License checking for the web component addon (CHARTS-106)

configuration-reader.html, demo/dynamic/click-to-add-point.html, demo/dynamic/events.html, demo/dynamic/master-detail-chart.html, demo/dynamic/xy-chart-selection.html, demo/line_and_scatter/basic-line-events.html, demo/line_and_scatter/date-axis-and-click-event.html, demo/line_and_scatter/spline-updating-each-second.html, demo/other/clock.html, test/chart-events-test.html, test/index.html, v-chart.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/44)
=> Add polymer events for Highcharts chart, series and point events (CHARTS-219)

configuration-reader.html, data-series.html, v-chart.html, valo-theme.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/45)
=> Update code documentation

demo/other/sparkline.html, vaadin-sparkline.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/48)
=> Only create sparkline when needed in demo (CHARTS-244)

chart-behavior.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/49)
=> Fix container div style declaration (CHARTS-206)

configuration-reader.html, demo/combination/column-line-pie.html, demo/combination/scatter-with-regression-lines.html, test/multiple-series-test.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/50)
=> Modified configuration-reader to read 'false' and 'true' as booleans 

chart-behavior.html, vaadin-sparkline.html
Also update chart behavior annotation
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/51)
=> Add doc to sparkline (CHARTS-228)

LICENSE.md, LICENSE.txt
License file should be in root and named LICENSE
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/55)
=> Follow convention for license file location (TB-39)

README.md, bower.json, package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/61)
=> Update remaining references to charts-component for vaadin-charts

bower.json, config/default.json, package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/63)
=> Change version to 3.0.0-alpha8

chart-behavior.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/68)
=> Rename _styleProperties do to conflict with Polymer 1.2.4 (CHARTS-329)

demo/index.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/67)
=> Fix demo viewport for mobile

bower.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/69)
=> Use license checker 0.9.1

chart-behavior.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/73)
=> Add fix for examples for ReactJS charts-379

bower.json, demo/other/sparkline.html, demo/sourcing-component.html
Update grid version.
Fix demo
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/74)
=> Fix sparkline demo (CHARTS-394)

demo/index.html
lite version is failing in the demo in IE
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/76)
=> Switch demo to non-lite version of polyfills (CHARTS-402)

demo/other/sparkline.html
Components cache was failing in IE
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/77)
=> Fix sparkline demo for IE (CHARTS-405)

bower.json, config/default.json, package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/78)
=> Update versions for beta1 release (CHARTS-213)

configuration-reader.html, test/chart-timeline.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/79)
=> Parse correctly stroke-width property (CHARTS-370)

vaadin-area-chart.html, vaadin-arearange-chart.html, vaadin-areaspline-chart.html, vaadin-areasplinerange-chart.html, vaadin-bar-chart.html, vaadin-boxplot-chart.html, vaadin-bubble-chart.html, vaadin-candlestick-chart.html, vaadin-column-chart.html, vaadin-columnrange-chart.html, vaadin-errorbar-chart.html, vaadin-flags-chart.html, vaadin-funnel-chart.html, vaadin-gauge-chart.html, vaadin-heatmap-chart.html, vaadin-line-chart.html, vaadin-ohlc-chart.html, vaadin-pie-chart.html, vaadin-polygon-chart.html, vaadin-pyramid-chart.html, vaadin-scatter-chart.html, vaadin-solidgauge-chart.html, vaadin-spline-chart.html, vaadin-treemap-chart.html, vaadin-waterfall-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/82)
=> Fix wrong quote in WC comment (CHARTS-425)

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/83)
=> Update license checker version

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/89)
=> Change version to 3.0.0-rc1

bower.json, framework-test/chart-angular1-test.html, framework-test/chart-jquery-test.html, framework-test/index.html, package.json
Added basic test for angular 1 binding support
Changed build config to run tests from both folders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/88)
=> New structure for framework tests (CHARTS-382)

demo/other/solid-gauge.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/87)
=> Fix solid gauge demo charts-418

bower.json, framework-test/chart-react-test.html, framework-test/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/90)
=> Added test for react integration

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/95)
=> Update version to 3.0.0

demo/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/100)
=> Add GA tracking for page load (CHARTS-469)

chart-behavior.html, configuration-reader.html, data-series.html, test/index.html, test/series-point-elements-mutation.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/102)
=> Add mutation for data element in data-series (CHARTS-459)

framework-test/chart-angular2-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/105)
=> Add Angular2 chart size test

config/default.json, tasks/cdn.js, tasks/zip.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/103)
=> Include directive in cdn deploy and directory zip (CHARTS-476)

bower.json, chart-behavior.html, test/chart-reload-test.html
Also add skipped folder for bower
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/104)
=> Chart element config was not reloaded in reloadConfiguration()

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/111)
=> Update angular beta 16

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/114)
=> Update version to 3.1.0-beta1

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/116)
=> Update angular beta 17

data-series.html, test/index.html, test/series-data-multiple-lines.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/115)
=> Replace line break with empty space in data-series data textContent

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/118)
=> Update version to 3.1.0-beta2 (CHARTS-491)

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/120)
=> Update license checker dependency

chart-behavior.html
Chart property should only be set by the chart component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/121)
=> Set chart property as readOnly and enable notify (CHARTS-493)

chart-behavior.html
Chart property should only be set by the chart component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/122)
=> Set chart property as readOnly and enable notify

demo/demo-picker.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/125)
=> Show Home page, API and Manual urls in demo

configuration-reader.html, data-series.html, test/chart-dynamic-import.html, test/index.html
When running vaadin charts with polymer-cli raised an exception
Fixes #126 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/128)
=> Fix problem with init with polymer-cli (charts-499)

gulpfile.js, package.json, tasks/demo.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/134)
=> Add demo war package task to gulp

react/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/133)
=> Identify vaadin-sparkline as vaadin-chart in react component

bower.json, demo/other/sparkline.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/136)
=> Update highcharts version to 4.2.6

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/138)
=> Update versions to 3.2.0

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/142)
=> Update to 4.0.0.alpha2

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/143)
=> Update version to 4.0.0-alpha3

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/144)
=> Update version to alpha4

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/146)
=> Update version to 4.0.0-beta1

bower.json, config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/148)
=> Update version to 4.0.0

.travis.yml, bower.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/149)
=> Fix test related versions

bower.json, chart-behavior.html, test/index.html, test/resize-test.html, test/x-resizable.html
Uses iron-resize-behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/151)
=> Add chart reflow on resize.

bower.json, framework-test/chart-jquery-test.html, framework-test/index.html, package.json, test/binding-test.html, test/chart-dynamic-import.html, test/chart-events-test.html, test/chart-flexbox-size.html, test/chart-load-event-test.html, test/chart-reload-test.html, test/chart-timeline.html, test/series-two-dimension-date-data.html, wct.conf.js
Update web components tester.
Use shadowRoot in element queries.
Add setTimeout, to wait that chart object is created properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/154)
=> Fix binding-test and chart-events-test

test/resize-test.html, test/x-resizable.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/158)
=> Fix resizable test

data-series.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/156)
=> Convert data series to class definition

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/159)
=> Update license checker to released version

configuration-reader.html, data-series.html
Left old definition of VaadinCharts.ConfigurationReaderBehavior for compatibility as it's used by VaadinCharts.ChartBehavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/160)
=> Update configuration reader to class mixin

configuration-reader.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/162)
=> Change mixin declaration for configuration reader

chart-behavior.html, configuration-reader.html
Add JSDoc to VaadinChart and VaadinChartsConfigurationReader classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/163)
=> Add JSDoc to converted classes

chart-behavior.html, valo-theme.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/164)
=> Convert Valo Theme behavior to expression mixin

bower.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/171)
=> Use latest stable versions

config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/176)
=> Update versions for 5.0.0-beta1 release

vaadin-sparkline.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/178)
=> Prevent error if data is undefined

vaadin-sparkline.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/179)
=> Sparkline should not animate

base-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/181)
=> Sync license version with project version

base-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/182)
=> Update licenseChecker product version to 5.0.0

config/default.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/183)
=> Update product version

wct.conf.js
Tests are not working due to wct problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/185)
=> Disabling ie11 tests.

bower.json, package.json, wct.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/186)
=> Update WCT and re-enable IE tests

bower.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/189)
=> Add license checker

analysis.json, demo/common.html, demo/index.html, demo/js-json-api.html, test/index.html, test/js-json-api-chart-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/192)
=> Added js JSON API and updated demo, docs and test

.travis.deploy.sh, .travis.yml
Add script that creates a war file for the 6.0-preview branch
and uploads it to app.fi server in order to show the
docs and demo pages.
Add task to Travis to make use of the new script.
CHARTS-613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/193)
=> Add task to deploy to app.fi server

.travis.yml
Added back ssh commands after fixing the output path of the unencrypted ssh key file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/196)
=> Fix Travis config file

test/performance/config.json, vaadin-chart.html
Add support to more chart types as seen at vaadin-charts 5.
Known issue:
- Colors are not working properly on some charts
Fixes #198
JIRA: CHARTS-619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/204)
=> Add more chart types

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/207)
=> Fix nodejs version to 8.1

.gitignore, package-lock.json, test/js-json-api-chart-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/208)
=> Inflate client-side function strings

analysis.json, demo/common.html, demo/element-api.html, demo/index.html, test/element-api-chart-test.html, test/index.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/210)
=> CHARTS-642: Title and Subtitle using the high-level Element API

test/js-json-api-chart-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/212)
=> Disable credits in the JSON API by default

test/visual/test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/215)
=> Increase gemini wait

README.md, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/216)
=> Update version to 6.0.0-alpha2

analysis.json, demo/js-api.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/217)
=> Fix JS API demo

demo/index.html, test/element-api-chart-series-dom-repeat-test.html, test/element-api-chart-test.html, test/index.html, test/js-json-api-chart-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/224)
=> Add demo and test for vaadin-chart-series in dom-repeat

vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/229)
=> Proper HC JS modules for styled mode / heatmap

README.md, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/228)
=> Update version to alpha3

package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/231)
=> Update version to v6.0.0-alpha4

analysis.json, vaadin-chart-series.html, vaadin-chart.html
Fixes #233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/234)
=> Use correct name for element classes

test/index.html, test/js-private-api-chart-test.html, vaadin-chart.html
This API is not public, but might be used by a server-side component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/232)
=> Add API allowing function calls on chart, axis, series and point level

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/238)
=> Add Google Chrome through apt

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/240)
=> Update build config

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/241)
=> Revert change in sudo requirement for build

package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/244)
=> update version to 6.0.0-alpha5

package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/248)
=> Update version to 6.0.0-alpha6

test/element-api-chart-series-dom-repeat-test.html, test/element-api-chart-series-json-test.html, test/element-api-chart-series-test.html, test/element-events-test.html, test/js-api-chart-test.html, test/js-json-api-chart-test.html, test/style-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/246)
=> Do not run before before HTMLImports are ready

README.md, bower.json, vaadin-chart.html
Checks Polymer version and reports usage statistics in development mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/249)
=> Use Vaadin.ElementMixin

vaadin-chart.html, vaadin-charts-default-theme.html
Fix growing issue by setting `display: block` to the svg element.
Description of the issue cause: https://github.com/highcharts/highcharts/issues/7494#issuecomment-350721804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/251)
=> Remove workaround to fix growing issue

package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/256)
=> Update version to 6.0.0-alpha7

bower.json, demo/flex-container.html
This is the result of the task to try to find issues with Vaadin Charts sizing task. 
I am not sure about the file location, that's why I didn't add to the demos menu, though it's in the demo folder. Suggestions are welcome.
JIRA: CHARTS-595
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/254)
=> Add a demo with vaadin-board

analysis.json, test/element-api-chart-series-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/257)
=>  Add custom event for point legend item click

README.md, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/259)
=> Update version to 6.0.0-alpha10

bower.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/261)
=> Use new license checker

README.md, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/263)
=> Update charts version

vaadin-chart-default-theme.html
* Fixes broken PieWithLegend demo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/264)
=> Default theme update with fixes from HighCharts

analysis.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/269)
=> Theming documentation update

README.md, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/272)
=> 6.0.0-alpha14

vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/273)
=> Add accessibility module

README.md, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/276)
=> v6.0.0-alpha15

vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/277)
=> Update JSDoc instruction to latest version

analysis.json, test/custom-property-test.html, test/element-height-test.html, test/index.html, vaadin-chart-default-theme.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/274)
=> Add css custom properties to make color theming even easier

README.md, analysis.json, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/280)
=> 6.0.0-alpha16

analysis.json, demo/index.html, test/element-api-chart-series-test.html, vaadin-chart-series.html
Add `type` attribute to `<vaadin-chart-series>` and make it observe any change in order to update the series properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/285)
=> Add type attribute to series element

analysis.json, demo/index.html, test/element-api-chart-series-test.html, test/element-api-chart-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/286)
=> Additional options on element

bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/287)
=> Ensure a working license checker is used

README.md, analysis.json, bower.json, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/289)
=> 6.0.0-beta1

vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/293)
=> Detect if Chart had already been initialized before connectedCallack

analysis.json
Analysis changes due to #293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/297)
=> Analysis update

.travis.yml, wct.conf.js
https://github.com/vaadin/vaadin-grid/issues/1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/300)
=> Pin quick tests to Chrome 64 on Windows 10 only

analysis.json, demo/index.html, test/element-api-chart-test.html, vaadin-chart.html
Add `categories` property to enable changing the labels on xAxis for `<vaadin-charts>`.
JIRA: CHARTS-643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/301)
=> Add categories property to vaadin-charts

test/element-api-chart-series-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/302)
=> Remove unused test property

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/304)
=> Add gitter button to readme

test/element-api-chart-series-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/306)
=> Test timing

analysis.json, test/element-api-chart-series-test.html, test/element-api-chart-test.html, test/element-json-merge-test.html, test/js-json-api-chart-test.html, test/style-test.html, test/theme-test.html, vaadin-chart.html
- Ensure charts can accept configuration updates even when not connected (essential for supporting chart-flow as a virtual child)
- Ensure that all buffered updates are applied when connected
- Drop dirty checking since we now buffer changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/309)
=> CHARTS-760: Chart should be usable as a virtual child

analysis.json, test/element-events-test.html, vaadin-chart.html
Update event names to make it more clear
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/311)
=> Add set extremes event for yAxis

analysis.json, bower.json, test/element-events-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/312)
=> Add set extremes events for X and Y axes

.travis.yml, README.md, analysis.json, test/element-api-chart-test.html, test/element-json-merge-test.html, test/js-json-api-chart-test.html, test/style-test.html, vaadin-chart.html, wct.conf.js
- 212c533 
- 2f37032 
- b0ed227 
- 952ca99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/315)
=> 6.1 backports

analysis.json, demo/index.html, test/element-api-chart-series-test.html, vaadin-chart-series.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/321)
=> Markers property on vaadin-chart-series

analysis.json, demo/index.html, test/element-api-chart-series-test.html, test/js-private-api-chart-test.html, vaadin-chart-series.html, vaadin-chart.html
JIRA: CHARTS-646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/322)
=> Add unit property to vaadin-chart-series

analysis.json, test/element-api-chart-series-test.html, test/element-api-chart-test.html, test/js-private-api-chart-test.html, vaadin-chart.html
JIRA: CHARTS-649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/332)
=> Add category-min attribute to vaadin-chart

analysis.json, test/element-api-chart-series-test.html, test/element-api-chart-test.html, test/js-json-api-chart-test.html, vaadin-chart.html
JIRA: CHARTS-650
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/333)
=> Add category-max to vaadin-chart

analysis.json, test/element-api-chart-series-test.html, vaadin-chart-series.html, vaadin-chart.html
CHARTS-689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/334)
=> Support value-max attribute for vaadin-chart-series

vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/339)
=> Fix conditional for false positives (min/max = 0)

vaadin-directory-description.md
Chery picking from #336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/341)
=> Adding description file for Vaadin Directory (#336)

bower.json
See more at https://github.com/Polymer/polymer/issues/5221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/344)
=> Pin shadycss to ~1.1.0 (#342)

bower.json
This reverts commit 2e8e26026fd57c0fe4042e747d97f1632e2dd82e.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/345)
=> Revert "Pin shadycss to ~1.1.0 (#342)"

bower.json
This reverts commit 3fdbb9805f8b2fbeacce69da0132b7733f669e11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/347)
=> Revert "Pin shadycss to ~1.1.0 (#342) (#344)"

analysis.json, test/element-api-chart-series-test.html, vaadin-chart-series.html
CHARTS-661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/349)
=> Support stack and stacking properties for series

wct.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/358)
=> Move IE11 and iOS to cron build

analysis.json, test/element-api-chart-series-test.html, vaadin-chart-series.html
Fixes #356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/359)
=> Add neck width attribute to series

analysis.json, test/element-api-chart-test.html, vaadin-chart.html
Add polar as boolean property to vaadin-chart element.
Fixes #364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/366)
=> Add polar property to vaadin-chart

test/theme-test.html, vaadin-chart.html
Fixes #365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/370)
=> Add support to hidden attribute

test/theme-test.html, vaadin-chart.html
* Add support to hidden attribute
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/376)
=> Add support to hidden attribute (#370)

magi-p3-post.json
magi now removes magi-p3-post file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/378)
=> remove section in post json is not needed anymore

analysis.json, vaadin-chart.html
* Adapt chart style to the flex status of container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/377)
=> Adjust chart style according to its container's flex status (#371)

analysis.json, test/element-api-chart-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/382)
=> CategoryPosition on vaadin-chart element

vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/387)
=> Create the default y-axis when needed

wct.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/392)
=> update safari version for tests

chart-exporting.js, test/exporting-test.html, test/index.html, vaadin-chart.html
Fixes #389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/394)
=> Fix for black chart exports and prints

README.md, analysis.json, package.json, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/396)
=> Prepare for 6.1.0-beta2 release

test/exporting-test.html, vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/397)
=> Lazily search for host selectors when exporting charts

bower.json, magi-p3-post.js, src/vaadin-chart.html
Use stables of other dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/411)
=> Update license checker

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/412)
=> Remove unused job

README.md, analysis.json, gulpfile.js, package.json, src/vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/413)
=> 6.2.0-alpha1

gulpfile.js, src/vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/415)
=> Fix vaadin-chart version

README.md, analysis.json, package.json, src/vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/423)
=> 6.2.0-alpha2 [skip ci]

README.md, analysis.json, package.json, vaadin-chart.html
Reverts vaadin/vaadin-charts#424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/425)
=> Revert "6.1.1"

bower.json, test/element-api-chart-test.html, test/exporting-test.html, vaadin-chart-default-theme.html
Reverts vaadin/vaadin-charts#422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/426)
=> Revert "Update Highcharts version (#421)"

README.md, package.json, src/vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/429)
=> Release 6.2.0

README.md, package.json, src/vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/430)
=> Version 6.2.1

bower.json, demo/charts-demo-app.html, index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/431)
=> Change demo page title, add side bar links and CTA, add Google Analytics

demo/charts-demo-app.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/432)
=> Re add Source code on Github section

bower.json, src/vaadin-chart-series.html, src/vaadin-chart.html, test/chart-in-layout-test.html, test/empty-chart-test.html, test/test-suites.js
Fixes https://github.com/vaadin/vaadin-charts-flow/issues/269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/434)
=> Prevent chart from overflowing the container area

src/vaadin-chart.html
🙊
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/436)
=> Fix disconnectedCallback in vaadin-chart

src/vaadin-chart-series.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/442)
=> Rollback changes in vaadin-chart-series

package.json, src/vaadin-chart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/443)
=> Version 6.2.2

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/444)
=> Fix API link in readme

chart-exporting.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/446)
=> Fix styling for `getSVG()` results

.travis.yml
Picked from https://github.com/vaadin/vaadin-element-skeleton/pull/205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/448)
=> chore(ci): pin Firefox version in travis to 66.0

bower.json, gulpfile.js, test/chart-in-layout-test.html, test/element-api-chart-series-dom-repeat-test.html, test/element-api-chart-series-json-test.html, test/element-api-chart-series-test.html, test/element-api-chart-test.html, test/element-dom-api-test.html, test/element-events-test.html, test/element-height-test.html, test/element-json-merge-test.html, test/empty-chart-test.html, test/index.html, test/js-api-chart-test.html, test/js-json-api-chart-test.html, test/js-private-api-chart-test.html, test/moving-chart-test.html, test/theme-test.html, vaadin-chart-series.html, vaadin-chart.html, wct.conf.js
- Prevent chart from overflowing the container area (#434) f403815
- Fix disconnectedCallback in vaadin-chart (#436) 4ee1057
- Move logic of removing series on disconnect (#449) d74db50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/451)
=> Apply last changes from master

test/element-events-test.html, test/js-api-chart-test.html, test/js-json-api-chart-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/454)
=> Update timeouts for tests to avoid safari failures

src/vaadin-chart-series.html, src/vaadin-chart.html
This will improve syntax highlighting e.g. in vaadin.com/components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/456)
=> docs: add missing language identifiers to code snippets

bower.json, src/vaadin-chart.html, theme/vaadin-chart-default-theme.html
=> Add RTL docs

src/vaadin-chart.html, test/js-private-api-chart-test.html
Add test setting Highcharts global options
=> Add static API to call Highcharts API

demo/charts-demo-app.html, demo/demos/timeline.html, src/vaadin-chart.html
Part of vaadin/vaadin-charts-flow#353
=> Add timeline support and demo to WC

demo/charts-demo-app.html, demo/common/demo-styles.html, demo/demos/bullet.html, demo/demos/xrange.html, src/vaadin-chart.html
=> Add modules and demos for xrange and bullet

bower.json, magi-p3-post.js, package-lock-p3.json, src/vaadin-chart.html
This should fix the case-sensitivity issue on Linux machines.
- Bugfix
=> fix: use uppercase version of DOMPurify dependency
