- tasks/zip.js
After this change the zip demos don't use the vulcanized v-chart
anymore.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/35)
> Fix paths for zip demos (CHARTS-194)

- chart-behavior.html
- data-series.html
- test/chart-using-javascript.html
If you create a chart using Javascript, then the light DOM
is not be setup when the ready is fired, and thus the chart
will always be empty.
This change modifies the behavior so the light DOM is ready when
the <vaadin-some-chart> is attached to the document. At this point
the light DOM must be ready.
Inner <data-series> cannot use the attached event as they are never attached
to the document, they are only added to the light DOM.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/53)
> Read light DOM configuration in attach instead of ready

- chart-behavior.html
- demo/combination/dual-charts.html
- test/chart-flexbox-size.html
- test/index.html
Chart now copies flex related style properties to chart container div
to ensure size calculations work in highcharts.
Style properties not related to flex are not copied and work correctly (CHARTS-184)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/charts-component/58)
> Fixed issue with flexbox layout (CHARTS-278)

- demo/column_and_bar/bar-with-negative-stack.html
- demo/line_and_scatter/basic-line-with-callouts.html
Fix data-labels tag for basic-line-with-callouts and
bar-with-negative-stack demos.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/75)
> Fix demos for IE11 charts-400

- configuration-reader.html
- demo/timeline/flags-placement.html
They worked as on-series element, but as propertyes polymer
considered them as event listeners
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/84)
> Add exception for onKey and onSeries properties (CHARTS-327)

- configuration-reader.html
- test/pie-config-test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/86)
> Fix parsing tags values always as strings charts-276

- configuration-reader.html
- data-series.html
Element properties are not initialized before element (data-series) is attached (https://github.com/Polymer/polymer/issues/1886).
Data-series must be initialized before it is attached because it is used only in light dom  (https://github.com/vaadin/vaadin-charts/commit/006b2f6ca7851f326e7daa5c539d1a6795ffff1d).
This fix is the most "proper fix".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/130)
> Proper fix for initing chart with polymer-cli

- bower.json
Previous tag was deleted from vaadin-grid repo, so bower building was failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/172)
> Fix vaadin-grid version

- test/resize-test.html
- test/x-resizable.html
This fix rollbacks some workaround to make this test pass after
upgrading to Polymer 2. Now it works as the old version used to
work, with <x-resizable> component being just a container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/173)
> Fix <vaadin-chart-resize> to work as the old version

- config/default.json
Deploy to cdn was missing some files because they were renamed in the conversion to mixins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/177)
> Update file names for cdn deploy

- .travis.yml
Keep only the `openssl` command added by Travis cli
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/195)
> Remove commands on Travis config file

- analysis.json
- vaadin-chart.html
- Make APIs doc one level lower
- Fix Highcharts API links
- Remove connectedCallback method from doc
Note that we are currently pointing to a newer version of Highcharts than we are using. This is due the fact that we still don't have our updated API doc site. We should update those links as soon we have a better option.
JIRA: CHARTS-590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/201)
> Add Basic Use section to JSDOC

- vaadin-chart.html
Because no tooltip is set while creating a new Highcharts instance,
calling update with a new config doesn't work as expected.
I filled an issue on Highcharts about that.
https://github.com/highcharts/highcharts/issues/7398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/223)
> Fix tooltip configuration

- vaadin-chart.html
`update` uses `Polymer.RenderStatus.beforeNextRender()` helper to enqueue the painting at `requestAnimationFrame` timing. But, when the tab is inactive, every task passed to `requestAnimationFrame` is delayed and they are only called once the tab is active again. 
This change is buffering the configuration in a way so that only the next render will use it and any other one after that can skip rendering the same configuration which was causing the tab to freeze sometimes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/230)
> Add accumulator for configuration object to prevent multiple draws

- wct.conf.js
iOS11 is supported by SauceLabs now. Updated one of the iOS devices to use it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/236)
> Add test against iOS 11

- vaadin-chart.html
Chart is growing on resize events if container height is not explicitly defined. This is related with a Highcharts issue on styled mode (https://github.com/highcharts/highcharts/issues/7494).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/247)
> Prevent chart from growing on window resize

- vaadin-chart.html
`ThemableMixin` is responsible of adding the theme to the component, so it turns out that leaving `include="vaadin-charts-default-theme"` is causing it to have duplicated styles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/253)
> Remove default theme from style

- test/style-test.html
- vaadin-chart-default-theme.html
- vaadin-chart.html
The Vaadin ThemableMixin would treat `vaadin-chartS-default-theme` as a custom theme for the `vaadin-chart` element. The default theme should be called `vaadin-chart-default-theme`. See [line 22](https://github.com/vaadin/vaadin-themable-mixin/blob/d6bb7cc0067fcacab132d65556e25903a0513098/vaadin-themable-mixin.html#L22) of the `Vaadin.ThemableMixin` definition for details.
When creating a custom theme for the `<vaadin-chart>` element it's ok to include `vaadin-chart-default-theme` if the custom theme is an extension of the default theme.
Related: https://github.com/vaadin/bakery-app-starter-flow-spring/pull/332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/255)
> fix the name of the detault theme for the vaadin-chart element

- .travis.yml
Travis is failing to run chrome-sandbox in non-sudo mode.
See https://github.com/vaadin/vaadin-element-skeleton/pull/90.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/260)
> Add sudo:true to Travis config

- vaadin-chart.html
Highcharts has an issue with flex container and shadow root, which
causes it to remove the chart container from the DOM tree.
This may be due the fact it can't properly calculate the size of
the chart container. Setting host width to 100% fixes this issue,
apparently.
JIRA: CHARTS-735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/262)
> Fix issue with component inserted in flex container

- vaadin-chart.html
After adding `accessibility` module, some errors started to happen for some chart types. It seemed to be an unexpected error related with which order `accessibility` and `highcharts-3d` modules are imported. Importing `accessibility` module before fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/279)
> Fix order of module imports

- test/element-dom-api-test.html
- test/element-height-test.html
- test/element-json-merge-test.html
- test/index.html
- vaadin-chart.html
Previously the way to merge configurations was to use `Object.assign`. The issue with that approach is that for Arrays it only takes the newest one. This PR attempt to prevent it by merging the configurations object within arrays for `series`, `xAxis` and `yAxis`. 
JIRA: CHARTS-704
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/275)
> Prevent multiple calls to update from overriding configuration

- test/index.html
- test/theme-test.html
- vaadin-chart-default-theme.html
Moved classes with custom css properties to their original location in Highcharts theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/307)
> Avoid overriding highcharts default theme with theme customization

- analysis.json
- test/element-api-chart-test.html
- vaadin-chart-series.html
- vaadin-chart.html
From polymer docs:
Attribute names with dashes are converted to camelCase property
names by capitalizing the character following each dash, then
removing the dashes.
For example, the attribute first-name maps to firstName.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/326)
> Use camelCase for property names

- analysis.json
- demo/index.html
- test/element-api-chart-test.html
- vaadin-chart.html
Tooltips are disabled by default. And can be enabled by adding the
tooltip attribute or by setting tooltip config in additional options
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/327)
> Add tooltip property

- test/element-events-test.html
- vaadin-chart.html
Axis afterSetExtremes is meaningless if axis is not defined.
Also helps prevent flow#3102
Fixes CHARTS-778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/337)
> Do not dispatch axis event if axis data is not available

- analysis.json
- test/element-api-chart-series-test.html
- vaadin-chart-series.html
* Add `neck-position` attribute to series
* Add observer to changes on neckPosition property
* Fix test for `neck-width`
* Previously tests were looking to `options` property from series, which is not valid, since it always compute from the current state. Change to check on `_series.options` object, which is the HC instance of the series.
Fixes #360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/361)
> Add neck-position to vaadin-chart-series

- analysis.json
- bower.json
- test/element-api-chart-test.html
- vaadin-chart.html
- HC 6.1.1 changed the way it calculates the xAxis with categories set with 3d.
- Change vaadin-chart to use chart3d on chart initialization.
- Set HC version to 6.1.0 because 6.1.1 isn't able to update a chart to 3d after creation, when there's xAxis.categories.
Context: https://github.com/highcharts/highcharts/issues/8555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/385)
> Fix HC version to 6.1.0

- src/vaadin-chart-series.html
- test/element-api-chart-test.html
- IE/Edge has parentNode not null even when the node is removed from its parent. This change checks either if parentNode is not present or if the browser is IE or Edge in order to call `this._series.remove()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/439)
> Test if IE/Edge on series disconnectedCallback

- polymer.json
- src/vaadin-chart.html
Connected to vaadin/components-team-tasks#492
This PR makes sure the license checker is only called when the component is created.
The static `_finalizeClass` method is needed to ensure we call it [once per class](https://github.com/Polymer/polymer/blob/f6ccc9d1bdc81e934e21bf27b3dba517b5840fd4/lib/mixins/properties-mixin.js#L138-L147).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-charts/461)
> refactor: only run license checker when needed

- src/vaadin-chart.html
- test/chart-in-rtl-test.html
- test/test-suites.js
Fixes #466
- Add workaround to prevent horizontal scrollbar appearing when charts is in RTL.
- Add test to check if the scrollWidth is affected by RTL
> fix(rtl): prevent horizontal scrollbar on RTL

- src/vaadin-chart-series.html
- src/vaadin-chart.html
- Remove Bower and npm instructions, we have them elsewhere (README, website tutorials)
- Actualise development mode popup description
- Remove outdated warning about Firefox and `remove()`
- Do not use "simply" as not recommended in docs
> docs: cleanup and actualize JSDoc

- @types/interfaces.d.ts
- bower.json
- chart-deep-merger.js
- gen-tsd.json
- magi-p3-post.js
- package.json
- src/vaadin-chart-series.html
- src/vaadin-chart.html
Fixes #467 
UPD: generated TS definitions looks like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {deepMerge, ChartElement} from './vaadin-chart.js';
declare class ChartSeriesElement extends PolymerElement {
readonly options: ChartSeriesOptions;
values: ChartSeriesValues|null;
valueMin: number|null;
valueMax: number|null;
type: string|null|undefined;
title: string;
markers: ChartSeriesMarkers|null|undefined;
unit: string|null|undefined;
stack: number|string;
neckPosition: number|string;
neckWidth: number|string;
additionalOptions: SeriesOptionsType|null|undefined;
setSeries(series: Series): void;
}
declare global {
interface HTMLElementTagNameMap {
"vaadin-chart-series": ChartSeriesElement;
}
}
export {ChartSeriesElement};
import …
```
> feat: prepare for TS defs generation

- src/vaadin-chart-series.html
- src/vaadin-chart.html
Connected to vaadin/vaadin-core#257
> docs: add JSDoc for attributes [skip ci]

- src/vaadin-chart.html
- test/element-api-chart-test.html
Fixes regression introduced by RTL workaround in 14.3 and 16 when disabling accessibility.
Fixes vaadin/vaadin-charts-flow#378
> Fix workaround for RTL issue

- src/vaadin-chart-series.html
- test/element-api-chart-series-test.html
- theme/vaadin-chart-default-theme.html
Migrated PR #558 to the repo so tests can run.
related to #474 
Workaround mentioned (highcharts/highcharts#13482) was already fixed in 8.1.1 (https://www.highcharts.com/blog/changelog/). 
Vaadin-charts already depend on 8.1.2.
> fix: enable accessibility for charts

- .github/workflows/unit-tests.yml
- .github/workflows/visual-tests.yml
- README.md
- package-lock.json
- package.json
- test/test-suites.js
- wct.conf.js
Fix a few issues with the project CI build:
- Move visual tests into `devDependencies` to be able to override `tough-cookie` dependency to a version supported by Node 12
- One of `gemini`'s dependency was too permissive about its own dependencies, which caused `tough-cookie@5.0.0` being picked, which does not support Node 12
- Update GH Actions to V4
- Disable W3C in the configuration for the Android Emulator test
- Disable the exporting tests as this was causing the test to timeout (it needs some investigation of its cause)
> chore: fix charts build
